SELECT DISTINCT 
category
FROM gold.dim_products

--DATABASE EXPLORATION
--Explore all objects in the database
 SELECT * FROM INFORMATION_SCHEMA.TABLES

 --Explore all columns in the database
 SELECT * FROM INFORMATION_SCHEMA.COLUMNS

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

--DATA EXPLORATION
--Explore all countries our customers come from
SELECT DISTINCT country FROM gold.dim_customers

--Explore all categories 'The major Divisions'
SELECT DISTINCT 
category,
subcategory,
product_name
FROM gold.dim_products
ORDER BY 1,2,3

--DATE EXPLORATION
--Explore earliest & latest date
SELECT 
MIN(order_date) First_order_date,
MAX(order_date) latest_order_date,
DATEDIFF(YEAR, MIN(order_date), MAX(order_date)) AS range_year,
DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS range_month
FROM gold.fact_sales

--Youngest & oldest Customres
SELECT 
MIN(birthdate) Youngest,
DATEDIFF(YEAR, MIN(birthdate), GETDATE()) oldest_age,
MAX(birthdate) Oldest,
DATEDIFF(YEAR, MAX(birthdate), GETDATE()) youngest_age
FROM gold.dim_customers

--MEASURES EXPLORATION - calculate key metrics of business;highest level of aggregation &
--lowest level of details; ca use sum, avg, 

--Find the total sales
SELECT 
SUM(sales_amount) 
FROM gold.fact_sales

-- Find how many items are sold
SELECT 
SUM(quantity) totalquantity
FROM gold.fact_sales

--Find avg selling price
SELECT 
AVG(price) avg_price
FROM gold.fact_sales

--Find total no of orders
SELECT 
COUNT(order_number) total_orders 
FROM gold.fact_sales

SELECT 
COUNT(DISTINCT order_number) total_orders -- eliminating duplicates by using Distinct
FROM gold.fact_sales

--Find total no of products
SELECT 
COUNT(product_key)
FROM gold.dim_products

--find total no of customers
SELECT 
COUNT(customer_key)
FROM gold.dim_customers

--find total no of customers placed an order
SELECT 
COUNT(DISTINCT customer_key)
FROM gold.fact_sales

--Generate the report for all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total No of Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total No of Products', COUNT(product_key) FROM gold.dim_products
UNION ALL
SELECT 'Total No of Customers', COUNT(customer_key) FROM gold.dim_customers

--MAGNITUDE ANALYSIS - compare measure values by categories - Measure/Dimension
-- ex: total sales/country; total quantity/ category; avg price/product; 
-- totalorders/customerrs

-- fimd total cutomers by countries
 SELECT
 country,
 COUNT(customer_key) total_customers
 FROM gold.dim_customers
 GROUP BY country
 ORDER BY total_customers DESC

 -- fimd total cutomers by gender 
 
 SELECT
 gender,
 COUNT(customer_key) total_customers
 FROM gold.dim_customers
 GROUP BY gender
 ORDER BY total_customers DESC

 -- find total products by category
SELECT
category,
COUNT(product_key) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--Find avg costs in each category?
SELECT
category,
AVG(cost) avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

--find total revenue generated by each category
SELECT
p.category,
SUM(s.sales_amount) total_sales
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_sales DESC

--find total revenue generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) total_sales
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_sales DESC

--what is the distribution of items sold across different countries?
SELECT
c.country,
SUM(s.quantity) total_items_sold
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_items_sold DESC

--Ranking Analysis - rank top/bottom N based on measure values
--Rank [dimension] by [measure]
-- ex: top 5 countries by total sales; top 10 products by quantity sold;

--Which 5 products generate the highest revenue?
SELECT TOP 5
p.product_name,
SUM(s.sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

--solving same using window functions - Row_number()
SELECT * FROM
(
SELECT
p.product_name,
SUM(s.sales_amount) total_revenue,
ROW_NUMBER() OVER (ORDER BY SUM(s.sales_amount) DESC) AS revenue_rank
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name
) t 
WHERE revenue_rank <= 5


--5 worst performing products by total sales
SELECT TOP 5
p.product_name,
SUM(s.sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC

--find top 10 customers generating highest revenue
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

--find lowest 3 customers with fewest orders placed
SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT s.order_number) total_orders
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_orders ASC
